"""third commit

Revision ID: e0a1e8e95420
Revises: dc9205457d62
Create Date: 2025-05-26 00:12:29.174144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a1e8e95420'
down_revision = 'dc9205457d62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
